version: "3.7"

services:

  flask:
    build: ./flask
    container_name: template_flask
    # restart: always
    environment:
      - APP_NAME=FlaskApp
    expose:
      - 8080
    depends_on:
      - db
      
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: db_name
      POSTGRES_USER: postgres_n
      POSTGRES_PASSWORD: postgres_p
    ports:
      - 5432:5432


  nginx:
    build: ./nginx
    container_name: template_nginx
    # restart: always
    ports:
      - "80:80"
      - "443:443"

    depends_on:
      - flask
  
  # additional 
  openvpn:
    cap_add:
     - NET_ADMIN
    image: kylemanna/openvpn
    container_name: openvpn
    ports:
     - "1194:1194/udp"
    restart: always
    volumes:
     - ./openvpn-data/conf:/etc/openvpn

